config/routes.rb
Rails.application.routes.draw do

  root to: 'web/admin/welcome#index'

  namespace :api do
    namespace :v1 do
      post '/auth/login', to: 'authentication#login'
      resources :statuses, only: :show
      resources :watchers do
        scope module: :watchers do
          resources :patients do
            scope module: :patients do
              resources :checklists
              resources :contacts
              resources :help_addresses
              resources :diets
              resources :histories
            end
          end
        end
      end
    end
  end

  scope module: :web do
    namespace :admin do
      resource :session, only: [:new, :create, :destroy]
      resources :admins
      resources :statuses
      resources :watchers
      resources :patients
      resources :categories
      resources :usefulvideos
      resources :usefultexts
      root 'welcome#index'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :patient

  validates :name, :location, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :email, uniqueness: true, email: true

  has_secure_password validations: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :usefulvideos, dependent: :destroy
  has_many :usefultexts, dependent: :destroy

  validates :name, :image_link, presence: true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :patient

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :patient

  validates :name, :phone_number, presence: true
end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :patient

  validates :description, presence: true
end

app/models/help_address.rb
class HelpAddress < ApplicationRecord
  belongs_to :patient

  validates :name, :location, presence: true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :status
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :watcher
  has_many :history, dependent: :nullify
  has_many :checklist, dependent: :destroy
  has_many :contact, dependent: :destroy
  has_many :help_address, dependent: :destroy

  has_secure_password validations: false
  validates :first_name, :last_name, :birthday, :password, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :history, dependent: :nullify
  validates :name, presence: true, uniqueness: true
end

app/models/useful_text.rb
class UsefulText < ApplicationRecord
  belongs_to :category

  validates :description, presence: true
end

app/models/useful_video.rb
class UsefulVideo < ApplicationRecord
  belongs_to :category

  validates :link, presence: true
end

app/models/watcher.rb
class Watcher < ApplicationRecord
  has_many :patients, dependent: :nullify

  validates :first_name, :last_name, :phone_number, :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :email, uniqueness: true, email: true

  has_secure_password validations: false
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  def not_found
    render json: { error: 'not_found' }
  end

  def authorize_request
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(header)
      @current_watcher = Watcher.find(@decoded[:watcher_id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: e.message }, status: :unauthorized
    end
  end
end

app/controllers/api/v1/statuses_controller.rb
class Api::V1::StatusesController < Api::V1::ApplicationController
  before_action :authorize_request, except: :create

  def index
    @statuses = Status.all
    render json: @statuses, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthHelper
end

app/controllers/concerns/auth_helper.rb
module AuthHelper
  def admin_sign_in(admin)
    session[:admin_id] = admin.id
  end

  def admin_sign_out
    session.delete(:admin_id)
  end

  def current_admin
    Admin.find_by(id: session[:admin_id])
  end

  def admin_sign_in?
    current_admin
  end

  def authenticate_admin!
    redirect_to new_admin_session_path unless admin_sign_in?
  end
end

app/controllers/web/admin/statuses_controller.rb
class Web::Admin::StatusesController < Web::Admin::ApplicationController
  def index
    @statuses = Status.all
  end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_attrs)
    if @status.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def show
    @status = Status.find(params[:id])
  end

  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])
    if @status.update(status_attrs)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    status = Status.find(params[:id])
    status.destroy

    redirect_to action: :index
  end

  private

  def status_attrs
    params.require(:status).permit(:name, patient_ids: [])
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  layout 'welcome/application'
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/web/admin/statuses/edit.html.haml
= simple_form_for @status, url: admin_status_path(@status.id) do |f|
  = f.input :name
  = f.button :submit, :class => "btn btn-outline-secondary"
  =link_to t('.cancel'), admin_statuses_path, :class => "btn btn-outline-secondary"

app/views/web/admin/statuses/index.html.haml
%table.table.table-striped.table-hover
  %tr
    %th= Status.human_attribute_name(:id)
    %th= Status.human_attribute_name(:name)
    %th= t('control')
  - @statuses.each do |status|
    %tr
      %td= status.id
      %td= status.name
      %td= link_to t('.view'), admin_status_path(status)
= link_to t('.back'), admin_root_path, :class => "btn btn-outline-secondary"
= link_to t('.create'), new_admin_status_path, :class => "btn btn-outline-secondary"

app/views/web/admin/statuses/new.html.haml
= simple_form_for @status, url: admin_statuses_path do |f|
  = f.input :name
  = f.button :submit, :class => "btn btn-outline-secondary"
  = link_to t('.cancel'), admin_statuses_path, :class => "btn btn-outline-secondary"

app/views/web/admin/statuses/show.html.haml
%table.table.table-striped.table-hover
  %tr
    %th= Status.human_attribute_name(:name)
  %tbody
    %tr
      %td=@status.name
= link_to t('.back'), admin_statuses_path, :class => "btn btn-outline-secondary"
= link_to t('.delete'), admin_status_path(@status.id), method: :delete, :class => "btn btn-outline-secondary"
= link_to t('.edit'), edit_admin_status_path(@status.id), :class => "btn btn-outline-secondary"